### ISSUE TITLE
SSTV Encoder v 2.1 Image orientation error di android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [olgamiller/SSTVEncoder2#1]
# Expected behavior
After taking a picture using the built-in camera on the device, then I clicked Ok to add an image. I should not have a problem with image orientation, and image orientation capability should be possible.

# Actual behavior
After taking a picture using the built-in camera on the device, then I clicked Ok to add an image. Suddenly there was a notification about the image orientation error.

# How to reproduce
* Launch app. 
* Click the camera icon, then take a picture. 
* Next click Ok to add the image.
* Then you will find the problem as I have explained. *Image orientation error.*

<center>Browser: Samsung Galaxy S6 edge
Operating system: Nougat 7.0
App version: 2.1</center>

# Recording Of The Bug
https://youtu.be/p7aLAED5aLM

# Logcat
<code>05-29 07:32:42.371  3707  9696 I WindowManager_SurfaceController: Destroying surface Surface(name=om.sstvencoder/om.sstvencoder.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2905 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1119 com.android.server.wm.WindowState.removeLocked:1860 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2928 com.android.server.wm.WindowManagerService.removeWindowLocked:2859 com.android.server.wm.WindowManagerService.removeWindowLocked:2683 com.android.server.wm.WindowManagerService.removeWindow:2678 com.android.server.wm.Session.remove:208 
05-29 07:32:42.371  3117  3187 I SurfaceFlinger: id=36 Removed NainActivit (4/7)
05-29 07:32:42.372  3117  6868 I SurfaceFlinger: id=36 Removed NainActivit (-2/7)
05-29 07:32:42.376  3707  9696 D InputTransport: Input channel destroyed: fd=414
05-29 07:32:42.378 14522 14522 D InputTransport: Input channel destroyed: fd=54
05-29 07:32:42.381  3117  4592 I SurfaceFlinger: id=32 Removed bnimation b (3/6)
05-29 07:32:42.382  3117  4591 I SurfaceFlinger: id=32 Removed bnimation b (-2/6)
05-29 07:32:42.432  7265 15028 I iu.UploadsManager: NEW; upload media id: 13037; iu: -1
05-29 07:32:42.458  6349  6882 W OpenGLRenderer: Incorrectly called buildLayer on View: CellLayoutChildren, destroying layer...
05-29 07:32:42.491  3707  4560 D MdnieScenarioControlService:  packageName : com.sec.android.app.launcher    className : com.sec.android.app.launcher.activities.LauncherActivity
05-29 07:32:42.556  7265 15028 I iu.UploadsManager: NEW; upload media id: 13038; iu: -1
05-29 07:32:42.650  7265 15028 I iu.UploadsManager: NEW; upload media id: 13040; iu: -1
05-29 07:32:42.725  7265 15028 I iu.UploadsManager: NEW; upload media id: 14613; iu: -1
05-29 07:32:42.800  7265 15028 I iu.UploadsManager: NEW; upload media id: 14622; iu: -1
05-29 07:32:42.870  7265 15028 I iu.UploadsManager: NEW; upload media id: 14627; iu: -1
05-29 07:32:42.943  7265 15028 I iu.UploadsManager: NEW; upload media id: 14628; iu: -1
05-29 07:32:43.022  7265 15028 I iu.UploadsManager: NEW; upload media id: 14631; iu: -1
05-29 07:32:43.092  7265 15028 I iu.UploadsManager: NEW; upload media id: 14632; iu: -1
05-29 07:32:43.150  3707  4590 D lights  : button : 0 +
05-29 07:32:43.163  7265 15028 W ExifParser: Tag 0000: Invalid data type 0
05-29 07:32:43.163  7265 15028 W ExifParser: Invalid link to next IFD: 741
05-29 07:32:43.169  7265 15028 I iu.UploadsManager: NEW; upload media id: 14633; iu: -1
05-29 07:32:43.188  3707  4590 D lights  : button : 0 -
05-29 07:32:43.246  7265 15028 I iu.UploadsManager: NEW; upload media id: 14635; iu: -1
05-29 07:32:43.322  7265 15028 I iu.UploadsManager: NEW; upload media id: 14636; iu: -1
05-29 07:32:43.402  7265 15028 I iu.UploadsManager: NEW; upload media id: 14642; iu: -1
05-29 07:32:43.410  3707  8524 D SSRM:s  : SIOP:: AP = 450, PST = 478 (W:10), CP = 493, CUR = -110, LCD = 46
05-29 07:32:43.412  3707  8524 D S       : broadcastSiopLevelIntent:: currentSiopLevel = 1
05-29 07:32:43.416 13270 13304 I SystemBroadcastReceiver: [#CMH#] Received broadcast 
05-29 07:32:43.416  3707  8524 D TelephonyManager: getAllCellInfo : Caller (PID / UID / TID): 3707 / 1000 / 8524
05-29 07:32:43.416 13270 13304 I PolicyManager: [#CMH#] onReceive action = EVENT_SIOP
05-29 07:32:43.416 13270 13304 I SystemBroadcastReceiver: [#CMH#] onReceive completed 
05-29 07:32:43.419  3707  3735 D CompatibilityInfo: mCompatibilityFlags - 0
05-29 07:32:43.419  3707  3735 D CompatibilityInfo: applicationDensity - 640
05-29 07:32:43.419  3707  3735 D CompatibilityInfo: applicationScale - 1.0
05-29 07:32:43.422 14621 14621 I [SC]DetectorReceiver: onReceive [com.samsung.intent.action.CHECK_SIOP_LEVEL]
05-29 07:32:43.424 14621 15039 I [SC]SystemStateMonitor: SIOP level : 1, is proper SIOP level : true
05-29 07:32:43.433 14731 14746 I SA      : [OCP]  URI : content://com.msc.openprovider.openContentProvider/tncRequest
05-29 07:32:43.434 14731 14964 I SA      : [OCP]  URI : content://com.msc.openprovider.openContentProvider/tncRequest
05-29 07:32:43.434 14731 14746 I SA      : [SCU] isHaveSA() - true
05-29 07:32:43.435 14731 14964 I SA      : [SCU] isHaveSA() - true
05-29 07:32:43.436 14731 14746 I SA      : [OCP]  Cursor is not null
05-29 07:32:43.437 14731 14964 I SA      : [OCP]  Cursor is not null
05-29 07:32:43.441 14621 15039 I [SC]CommonUtil: email : 0 tncState :0 nameCheckState : 0 emailValidationState : 0
05-29 07:32:43.442 14621 15041 I [SC]CommonUtil: email : 0 tncState :0 nameCheckState : 0 emailValidationState : 0
05-29 07:32:43.501  7265 15028 I iu.UploadsManager: NEW; upload media id: 14643; iu: -1
05-29 07:32:43.576  7265 15028 I iu.UploadsManager: NEW; upload media id: 14645; iu: -1
05-29 07:32:43.671  7265 15028 I iu.UploadsManager: NEW; upload media id: 14653; iu: -1
05-29 07:32:43.803  7265 15028 I iu.UploadsManager: NEW; upload media id: 14654; iu: -1
05-29 07:32:43.943  7265 15028 I iu.UploadsManager: NEW; upload media id: 14659; iu: -1
05-29 07:32:44.238  7265 15028 I iu.UploadsManager: NEW; upload media id: 14660; iu: -1
05-29 07:32:44.331  5640  5640 D io_stats: !@   8,0 r 156298 7010372 w 22660 329796 d 1532 104588 f 9050 9050 iot 52360 47348 th 61440 0 0 pt 0 inp 0 0 182.511
05-29 07:32:44.355  7265 15028 I iu.UploadsManager: NEW; upload media id: 14662; iu: -1
05-29 07:32:44.535  7265 15028 I iu.UploadsManager: NEW; upload media id: 14694; iu: -1
05-29 07:32:44.760  3707  8524 D S       : limitCPUFreq:: freq = 1600000
05-29 07:32:44.762  3707  8524 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MAX_LIMIT  frequency : 1600000  uid : 1000  pid : 3707  pkgName : SIOP_ARM_MAX@20
05-29 07:32:44.764  3707  8524 D S       : limitGPUFreq:: freq = 350
05-29 07:32:44.776  3707  8524 D TelephonyManager: getAllCellInfo : Caller (PID / UID / TID): 3707 / 1000 / 8524
05-29 07:32:44.801  7265 15028 I iu.UploadsManager: NEW; upload media id: 14699; iu: -1
05-29 07:32:44.885  6349  6349 D capture : captureMainHomeScreen
05-29 07:32:44.885  6349  6349 D capture : canCapture isWorkspaceLocked() = false isVisible : false
05-29 07:32:44.885  6349  6349 D capture : canCapture mWorkspace.getState()() = NORMAL isTouchActive : false isPageMoving : false
05-29 07:32:44.906  7265 15028 I iu.UploadsManager: NEW; upload media id: 14701; iu: -1
05-29 07:32:45.017  7265 15028 I iu.UploadsManager: NEW; upload media id: 14702; iu: -1
05-29 07:32:45.340  3707  4603 D skia    : Encode PNG Singlethread :     544239 us, width=864, height=1478
05-29 07:32:45.411  7265 15028 I iu.UploadsManager: NEW; upload media id: 14703; iu: -1
05-29 07:32:45.417 13270 13308 I ReschedulableTimer: [#CMH#] ReschedulableTimer started 
05-29 07:32:45.517  7265 15028 I iu.UploadsManager: NEW; upload media id: 14704; iu: -1
05-29 07:32:45.689  7265 15028 I iu.UploadsManager: NEW; upload media id: 14709; iu: -1
05-29 07:32:45.823  4668  4889 D NetworkController.MobileSignalController(0/6): onSignalStrengthsChanged signalStrength=SignalStrength: 9 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 0x4 gsm|lte level=4
05-29 07:32:45.823  4668  4889 D NetworkController.MobileSignalController(0/6): getMobileIconGroup(): 8
05-29 07:32:45.868  7265 15028 I iu.UploadsManager: NEW; upload media id: 14711; iu: -1
05-29 07:32:46.017  7265 15028 I iu.UploadsManager: NEW; upload media id: 14713; iu: -1
05-29 07:32:46.233  7265 15028 I iu.UploadsManager: NEW; upload media id: 14715; iu: -1
05-29 07:32:46.408  7265 15028 I iu.UploadsManager: NEW; upload media id: 14716; iu: -1
05-29 07:32:46.628  7265 15028 I iu.UploadsManager: NEW; upload media id: 14718; iu: -1</code>

**Comment by olgamiller** [comment]
Hello Ammar.

Thank you for the detailed bug report.
This issue should be fixed now. Please see [Release Version 2.2](https://github.com/olgamiller/SSTVEncoder2/releases/tag/Version2.2). 

Best regards,
Olga
