### ISSUE TITLE
вопрос по формату

### ISSUE THREAD

**Issue by Slamfox** [olgamiller/SSTVEncoder2#11]
здравствуйте, пишу диплом в данный моммент с использованием вашей программы 
хотелось бы узнать какой формат изображений поддерживает приложение сколько на сколько пикселей
и еще для усовершенствования программы нужен код программы 
не могли бы вы его предоставить ???

**Comment by olgamiller** [comment]
Hello. The image format is not limited, at least not explicitly. The size is limited by bufferBytes = 1048576 (I'm working on removing the size limit by replacing BitmapFactory.decodeStream with another method). The entire code is in this repository, see loadImage in CropView.java. Does it answer your questions?

**Comment by Slamfox** [comment]
ThanksОтправлено с iPhone4 марта 2023 г., в 21:09, Olga Miller ***@***.***> написал(а):﻿
Hello. The image format is not limited, at least not explicitly. The size is limited by bufferBytes = 1048576 (I'm working on removing the size limit by replacing BitmapFactory.decodeStream with another method). The entire code is in this repository, see loadImage in CropView.java. Does it answer your questions?

**Comment by Slamfox** [comment]
Привет, не могу найти исходный код , не могли бы отправить ссылку?И еще вопрос, я для диплома ищу программиста который бы помог с приложением , у вас случайно нет такой возможности ? Объясню суть того что необходимо сделать:Необходимо оьъеденить sstv encoder and robot36, чтобы можно было как отправлять так и принимать щображения с помощью одного приложения + поверх поставить кодирование изображения (она готова )Даже готов за какую то плату, чтобы вы помогли или может быть знаете того кто бы мог это сделатьСпасибо!Отправлено с iPhone4 марта 2023 г., в 21:09, Olga Miller ***@***.***> написал(а):﻿
Hello. The image format is not limited, at least not explicitly. The size is limited by bufferBytes = 1048576 (I'm working on removing the size limit by replacing BitmapFactory.decodeStream with another method). The entire code is in this repository, see loadImage in CropView.java. Does it answer your questions?

**Comment by olgamiller** [comment]
Hi, here is the link to the MainActivity (if it's what you mean): https://github.com/olgamiller/SSTVEncoder2/blob/master/app/src/main/java/om/sstvencoder/MainActivity.java
Sorry, I do not know a developer who would like to implement the request.
