### ISSUE TITLE
add "Reset-Image-Position" Button（NewFeatureAdvise）

### ISSUE THREAD

**Issue by Redroadsl** [olgamiller/SSTVEncoder2#14]
Please add a button to reset image position to center，or I have to reload the image by open it twice(it's annoying)
![Screenshot_20230805_204433_om sstvencoder](https://github.com/olgamiller/SSTVEncoder2/assets/50506568/dc8c9e99-fb9f-4189-a4c7-8400e43e9efb)

**Comment by olgamiller** [comment]
Thank you for the suggestion.
In the version 2.9, an option "Transform Image" > "Reset" has been added.
