### ISSUE TITLE
Improvement idea: Real PTT for SSTV Encoder App?

### ISSUE THREAD

**Issue by DE8MSH** [olgamiller/SSTVEncoder2#16]
Hello.

Out there's an interface called AOIC: https://github.com/skuep/AIOC on the market.

This hardware is able to use PTT on ttyACM port. What do you think? Is this PTT function interesting for you, too? AIOC has proparitary VOX PTT function implemented only. I think real PTT on ttyACM port would be really great. Because amateur operators prefering real PTT.

I'd test it for you. :)

Thank you very much for rating this idea. 

de DO7OO

**Comment by olgamiller** [comment]
Hello, thank you. 
However, please note that an issue with PTT suggestion already exists: [https://github.com/olgamiller/SSTVEncoder2/issues/12](url)
