### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [olgamiller/SSTVEncoder2#5]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by olgamiller** [comment]
Thank you for pointing it out, but I do not like to put any screenshots into this Git repository.

**Comment by olgamiller** [comment]
Added the app icon and phoneScreenshots (it is rather not expected that they will need to be changed often, so should be fine).
Thanks again for the info.
