### ISSUE TITLE
Flashlight PTT

### ISSUE THREAD

**Issue by kj7rrv** [olgamiller/SSTVEncoder2#6]
Hello,
I'm working on a radio-computer interface designed specifically for connecting smartphones to HTs, using the phone's flashlight for PTT. Would you consider adding an option to turn the flashlight on before ech transmission and back off at the end? I can try to write a PR when I have time, but I'm not very good with Java.

Disclosure: I do intend to sell these interfaces if they work well enough.

73

**Comment by olgamiller** [comment]
Hello,
I do not have time to add and test this feature.
If you want to provide a PR, then please also test the feature on various devices with different Android versions.
Thank you.

**Comment by kj7rrv** [comment]
Okay, thank you. I will try to write a PR when I can.Testing will not be a problem. I have several phones (mostly cheap Tracfones) on several different versions of Android, and I will test it on all of them.

**Comment by kj7rrv** [comment]
:%s/Okat/Okay/gOn May 14, 2021 11:13, Sam Sloniker ***@***.***> wrote:Okat, thank you. I will try to write a PR when I can.Testing will not be a problem. I have several phones (mostly cheap Tracfones) on several different versions of Android, and I will test it on all of them.On May 14, 2021 10:49, Olga Miller ***@***.***> wrote:
Hello,
I do not have time to add and test this feature.
If you want to provide a PR, then please also test the feature on various devices with different Android versions.
Thank you.
