### ISSUE TITLE
Cannot take picture on Android 11

### ISSUE THREAD

**Issue by kj7rrv** [olgamiller/SSTVEncoder2#7]
When I try to take a picture from the app, it lets me take the picture, but then it resets to the color bars and says "Image loading error: open failed: ENOENT (no such file or directory)". It did work until my phone updated from 10 to 11.
It's not that big of a deal for me, because I usually take a picture from my camera app and open it from photos anyway, so don't worry too much about this unless you or someone else uses it enough for this to be a problem.
73, Sam KJ7RRV

**Comment by olgamiller** [comment]
Thank you for reporting the issue.

**Comment by kj7rrv** [comment]
Let me know if there is anything I can test. I'm perfectly happy to sideload a debug version.

**Comment by olgamiller** [comment]
Great, thanks.

**Comment by olgamiller** [comment]
Could you please try again with the latest version?

**Comment by Sceeker** [comment]
I don't have any error, but I still can't use this functionality either. There is no prompt from Android about giving permission to the app, and the app infos say the app uses no permission at all. Clicking on the photos button does nothing.
Thanks

**Comment by olgamiller** [comment]
Thank you for testing it.
With the commit [8ce13b9fc509429b0e8f40fadb49f731d6e22535](https://github.com/olgamiller/SSTVEncoder2/commit/8ce13b9fc509429b0e8f40fadb49f731d6e22535) it should be fixed.
