### ISSUE TITLE
After clicking the camera button, the app crashes

### ISSUE THREAD

**Issue by YYYSSSHHH** [olgamiller/SSTVEncoder2#9]
### Environment Info：
APK Version:  2.5 (26)
Android simulator version: 6.0.1

When  "WRITE_EXTERNAL_STORAGE"permission is granted,  clicked the "camera" button,  app crashs. 
![SSTcrash](https://user-images.githubusercontent.com/55122523/124084958-1ce05680-da82-11eb-9f2e-84c02697ee6d.png)

It may be that apk does not declare "CAMERA" permission ,  which causes this problem.
If you solve the bug, please tell me the cause.

**Comment by olgamiller** [comment]
Thank you for reporting the issue.
